server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /
---
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.gyex.webwite.entity
---
spring:
  datasource:
    name: website
    url: jdbc:mysql://192.168.253.1:3306/website?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
